export const PRODUCT_ACTIONS = {

  SET_LOADING:"SET_LOADING",

  SET_ERROR:"SET_ERROR",

  SET_PRODUCTS:"SET_PRODUCTS",

  SET_FILTERED_PRODUCTS:"SET_FILTERED_PRODUCTS",

  SET_CATEGORIES:"SET_CATEGORIES",

  SET_BRANDS:"SET_BRANDS",

  SET_SELECTED_CATEGORY:"SET_SELECTED_CATEGORY",

  SET_SELECTED_BRANDS:"SET_SELECTED_BRANDS",

  SET_PRICE_RANGE:"SET_PRICE_RANGE",

  SET_PAGE:"SET_PAGE",

  RESET_FILTERS:"RESET_FILTERS"

}